apiVersion: notification-ctrlr.netop-types.io/v1alpha1
kind: Notification
metadata:
  creationTimestamp: null
  name: f1-c1-calico-netop-manager-system-cko-argo-secret-core-v1
spec:
  clusterName: F1_C1_Calico
  objRef:
    apiVersion: v1
    kind: Secret
    name: cko-argo
    namespace: netop-manager-system
  serializedObj: '{"kind":"Secret","apiVersion":"v1","metadata":{"name":"cko-argo","namespace":"netop-manager-system","creationTimestamp":null},"data":{"password":"bjFMaTQzQThITWow","type":"Z2l0","url":"aHR0cHM6Ly9naXRodWIuY29tL2NhbXJvc3NpL2Nrby1jbHVzdGVycw==","username":"Y2Ftcm9zc2k="},"type":"Opaque"}'
status:
  state: ""
