apiVersion: netop.mgr/v1alpha1
kind: ClusterInfo
metadata:
  creationTimestamp: "2023-01-30T12:25:01Z"
  finalizers:
  - netop.mgr/finalizer
  generation: 1176
  managedFields:
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"netop.mgr/finalizer": {}
    manager: ansible-operator
    operation: Update
    time: "2023-01-30T12:25:01Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:ownerReferences:
          .: {}
          k:{"uid":"31aa88f0-1e39-45f0-87e2-d503874a1cd0"}: {}
      f:spec:
        .: {}
        f:config_overrides:
          .: {}
          f:aci_cni_config:
            .: {}
            f:aci_config:
              .: {}
              f:vmm_domain:
                .: {}
                f:mcast_range: {}
                f:nested_inside: {}
            f:kube_config:
              .: {}
              f:drop_log_config: {}
              f:istio_config: {}
              f:multus: {}
              f:nodepodif_config: {}
              f:operator_managed_config: {}
              f:sriov_config: {}
            f:logging: {}
            f:net_config: {}
            f:registry: {}
          f:aci_config:
            .: {}
            f:cluster_l3out:
              .: {}
              f:bgp:
                .: {}
                f:peering: {}
              f:svi: {}
            f:l3out: {}
            f:physical_domain: {}
            f:vrf: {}
          f:calico_cni_config:
            .: {}
            f:target_version: {}
          f:cko_proxy_config: {}
          f:cni: {}
          f:connectivity_checker:
            .: {}
            f:reachability_test_enable:
              .: {}
              f:external_url: {}
              f:periodic_sync: {}
          f:context:
            .: {}
            f:l3out:
              .: {}
              f:external_networks: {}
              f:name: {}
            f:vrf:
              .: {}
              f:name: {}
              f:tenant: {}
          f:distro: {}
          f:fabricinfra:
            .: {}
            f:name: {}
          f:gitops:
            .: {}
            f:base64_encoded_argo_manifests: {}
          f:lb_config: {}
          f:monitoring_config: {}
          f:net_config:
            .: {}
            f:cluster_svc_subnet: {}
            f:extern_dynamic: {}
            f:node_subnet: {}
            f:pod_subnet: {}
          f:operator_config:
            .: {}
            f:mode: {}
          f:profile: {}
          f:registry: {}
          f:service_mesh_config: {}
          f:topology:
            .: {}
            f:rack: {}
    manager: manager
    operation: Update
    time: "2023-01-30T12:51:38Z"
  name: ckof1c1
  namespace: netop-manager
  ownerReferences:
  - apiVersion: netop.mgr/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ClusterProfile
    name: ckof1c1
    uid: 31aa88f0-1e39-45f0-87e2-d503874a1cd0
  resourceVersion: "12917590"
  uid: bb919195-6719-4f7c-9530-efc0c241b477
spec:
  config_overrides:
    aci_cni_config:
      aci_config:
        vmm_domain:
          mcast_range: {}
          nested_inside: {}
      kube_config:
        drop_log_config: {}
        istio_config: {}
        multus: {}
        nodepodif_config: {}
        operator_managed_config: {}
        sriov_config: {}
      logging: {}
      net_config: {}
      registry: {}
    aci_config:
      cluster_l3out:
        bgp:
          peering: {}
        svi: {}
        vrf: {}
      l3out: {}
      physical_domain: {}
      vrf: {}
    calico_cni_config:
      target_version: v3.25.0
    cko_proxy_config: {}
    cni: calico
    connectivity_checker:
      reachability_test_enable:
        external_url: {}
        periodic_sync: {}
    context:
      l3out:
        external_networks:
        - default_extepg
        name: default
      vrf:
        name: default
        tenant: common
    distro: {}
    fabricinfra:
      name: fab1
    gitops:
      base64_encoded_argo_manifests: ""
    lb_config: {}
    monitoring_config: {}
    net_config:
      cluster_svc_subnet: 10.96.0.0/12
      extern_dynamic: 192.168.24.0/24
      node_subnet: 192.168.15.16/28
      pod_subnet: 192.168.23.0/24
    operator_config:
      mode: managed
    profile: {}
    registry: {}
    service_mesh_config: {}
    topology:
      rack:
      - aci_pod_id: 1
        id: 1
        leaf:
        - id: 101
          local_ip: 192.168.15.28
        - id: 102
          local_ip: 192.168.15.27
        node:
        - name: ckof1c1-master-1
        - name: ckof1c1-master-2
        - name: ckof1c1-master-3
status:
  status: false
