apiVersion: netop.mgr/v1alpha1
kind: ClusterProfile
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"netop.mgr/v1alpha1","kind":"ClusterProfile","metadata":{"annotations":{},"name":"ckof1c1","namespace":"netop-manager"},"spec":{"cluster_name":"ckof1c1","cluster_network_profile_selector":{"matchLabels":{"cluster_name":"ckof1c1"}},"config_overrides":{"calico_cni_config":{"target_version":"v3.25.0"}}}}
  creationTimestamp: "2023-01-30T12:25:01Z"
  finalizers:
  - clusterprofile.netop.mgr/finalizer
  generation: 3
  managedFields:
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"clusterprofile.netop.mgr/finalizer": {}
      f:spec:
        f:config_overrides:
          .: {}
          f:aci_cni_config:
            .: {}
            f:aci_config:
              .: {}
              f:vmm_domain:
                .: {}
                f:mcast_range: {}
                f:nested_inside: {}
            f:kube_config:
              .: {}
              f:drop_log_config: {}
              f:istio_config: {}
              f:multus: {}
              f:nodepodif_config: {}
              f:operator_managed_config: {}
              f:sriov_config: {}
            f:logging: {}
            f:net_config: {}
            f:registry: {}
          f:aci_config:
            .: {}
            f:cluster_l3out:
              .: {}
              f:bgp:
                .: {}
                f:peering: {}
              f:svi: {}
            f:l3out: {}
            f:physical_domain: {}
            f:vrf: {}
          f:calico_cni_config: {}
          f:cko_proxy_config: {}
          f:connectivity_checker:
            .: {}
            f:reachability_test_enable:
              .: {}
              f:external_url: {}
              f:periodic_sync: {}
          f:gitops:
            .: {}
            f:base64_encoded_argo_manifests: {}
          f:lb_config: {}
          f:monitoring_config: {}
          f:net_config: {}
          f:registry: {}
          f:service_mesh_config: {}
        f:distro: {}
        f:fabricinfra: {}
        f:operator_config:
          .: {}
          f:mode: {}
    manager: manager
    operation: Update
    time: "2023-01-30T12:25:01Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:cluster_name: {}
        f:cluster_network_profile_selector: {}
        f:config_overrides:
          f:calico_cni_config:
            f:target_version: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2023-01-30T12:51:38Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:aci_cni_config: {}
        f:assigned_subnets:
          .: {}
          f:cluster_svc_subnet: {}
          f:extern_dynamic: {}
          f:node_subnet: {}
          f:pod_subnet: {}
        f:calico_cni_config:
          .: {}
          f:version: {}
        f:cluster_network_profile_name: {}
        f:context:
          .: {}
          f:l3out:
            .: {}
            f:external_networks: {}
            f:name: {}
          f:vrf:
            .: {}
            f:name: {}
            f:tenant: {}
        f:fabricinfra:
          .: {}
          f:context: {}
          f:name: {}
        f:operator_config:
          .: {}
          f:mode: {}
        f:ready: {}
        f:remote_as_numbers: {}
        f:vlans: {}
        f:workload_cluster_manifest_locations: {}
    manager: manager
    operation: Update
    subresource: status
    time: "2023-01-30T12:51:38Z"
  name: ckof1c1
  namespace: netop-manager
  resourceVersion: "12439841"
  uid: 31aa88f0-1e39-45f0-87e2-d503874a1cd0
spec:
  cluster_name: ckof1c1
  cluster_network_profile_selector:
    matchLabels:
      cluster_name: ckof1c1
  config_overrides:
    aci_cni_config:
      aci_config:
        vmm_domain:
          mcast_range: {}
          nested_inside: {}
      kube_config:
        drop_log_config: {}
        istio_config: {}
        multus: {}
        nodepodif_config: {}
        operator_managed_config: {}
        sriov_config: {}
      logging: {}
      net_config: {}
      registry: {}
    aci_config:
      cluster_l3out:
        bgp:
          peering: {}
        svi: {}
        vrf: {}
      l3out: {}
      physical_domain: {}
      vrf: {}
    calico_cni_config:
      target_version: v3.25.0
    cko_proxy_config: {}
    connectivity_checker:
      reachability_test_enable:
        external_url: {}
        periodic_sync: {}
    gitops:
      base64_encoded_argo_manifests: ""
    lb_config: {}
    monitoring_config: {}
    net_config: {}
    registry: {}
    service_mesh_config: {}
  distro: {}
  fabricinfra: {}
  operator_config:
    mode: managed
status:
  aci_cni_config: {}
  assigned_subnets:
    cluster_svc_subnet: 10.96.0.0/12
    extern_dynamic: 192.168.24.0/24
    node_subnet: 192.168.15.16/28
    pod_subnet: 192.168.23.0/24
  calico_cni_config:
    version: v3.25.0
  cluster_network_profile_name: networkprofile-ckof1c1
  context:
    l3out:
      external_networks:
      - default_extepg
      name: default
    vrf:
      name: default
      tenant: common
  fabricinfra:
    context: auto-ckof1c1
    name: fab1
  operator_config:
    mode: managed
  ready: true
  remote_as_numbers:
  - 64512
  vlans:
  - 101
  workload_cluster_manifest_locations:
  - 'argo: https://github.com/camrossi/cko-clusters/tree/main/workload/argo/ckof1c1'
  - 'operator: https://github.com/camrossi/cko-clusters/tree/main/workload/config/ckof1c1'
