apiVersion: netop.mgr/v1alpha1
kind: FabricInfra
metadata:
  creationTimestamp: "2023-02-02T05:51:20Z"
  finalizers:
  - fabricinfra.netop.mgr/finalizer
  generation: 2
  labels:
    fabric: fab2
    site: stld
  managedFields:
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:fabric: {}
          f:site: {}
      f:spec:
        .: {}
        f:bgp:
          .: {}
          f:aci_as_number: {}
          f:remote_as_numbers: {}
        f:contexts:
          .: {}
          f:context-1:
            .: {}
            f:aep: {}
            f:l3out:
              .: {}
              f:external_networks: {}
              f:name: {}
            f:vrf:
              .: {}
              f:name: {}
              f:tenant: {}
          f:context-2:
            .: {}
            f:aep: {}
            f:l3out:
              .: {}
              f:external_networks: {}
              f:name: {}
            f:vrf:
              .: {}
              f:name: {}
              f:tenant: {}
        f:credentials:
          .: {}
          f:hosts: {}
          f:secretRef:
            .: {}
            f:name: {}
        f:external_subnets: {}
        f:fabric_type: {}
        f:infra_vlan: {}
        f:internal_subnets: {}
        f:mcast_subnets: {}
        f:vlans: {}
    manager: kubectl-create
    operation: Update
    time: "2023-02-02T05:51:20Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"fabricinfra.netop.mgr/finalizer": {}
      f:spec:
        f:topology: {}
    manager: manager
    operation: Update
    time: "2023-02-02T05:51:20Z"
  - apiVersion: netop.mgr/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:allocated: {}
        f:available:
          .: {}
          f:contexts:
            .: {}
            f:context-1:
              .: {}
              f:aep: {}
              f:l3out:
                .: {}
                f:external_networks: {}
                f:name: {}
              f:vrf:
                .: {}
                f:name: {}
                f:tenant: {}
            f:context-2:
              .: {}
              f:aep: {}
              f:l3out:
                .: {}
                f:external_networks: {}
                f:name: {}
              f:vrf:
                .: {}
                f:name: {}
                f:tenant: {}
          f:external_subnets: {}
          f:internal_subnets: {}
          f:mcast_subnets: {}
          f:remote_as_numbers: {}
          f:vlans: {}
        f:ready: {}
    manager: manager
    operation: Update
    subresource: status
    time: "2023-02-17T01:49:23Z"
  name: fab2
  namespace: netop-manager
  resourceVersion: "5090903"
  uid: 4c5f0e91-e11a-4e86-bba3-c414f1565346
spec:
  bgp:
    aci_as_number: 65002
    remote_as_numbers:
    - 64512
    - 64513
    - 64514
  contexts:
    context-1:
      aep: ACI_AttEntityP
      l3out:
        external_networks:
        - default_extepg
        name: l3out
      vrf:
        name: k8s
        tenant: common
    context-2:
      aep: ACI_AttEntityP
      l3out:
        external_networks:
        - default_extepg
        name: l3out
      vrf:
        name: k8s
        tenant: common
  credentials:
    hosts:
    - fab2-apic1.cam.ciscolabs.com
    - fab2-apic2.cam.ciscolabs.com
    - fab2-apic3.cam.ciscolabs.com
    secretRef:
      name: apic-credentials
  external_subnets:
  - 10.3.0.1/16
  - 10.4.0.1/16
  - 20.3.0.1/16
  - 20.4.0.1/16
  fabric_type: aci
  infra_vlan: 3456
  internal_subnets:
  - 1.100.101.1/16
  - 2.100.101.1/16
  - 10.5.0.1/16
  - 10.6.0.1/16
  - 20.2.0.1/16
  - 20.5.0.1/16
  mcast_subnets:
  - 225.114.0.0/16
  - 225.115.0.0/16
  topology: {}
  vlans:
  - 101
  - 102
  - 103
  - 104
status:
  allocated:
  - cluster_group_profile: f2acicni
    cluster_profile: ckof2c1
    context:
      aep: ACI_AttEntityP
      l3out:
        external_networks:
        - default_extepg
        name: l3out
      vrf:
        name: k8s
        tenant: common
    external_subnets:
    - 10.3.0.1/16
    - 10.4.0.1/16
    internal_subnets:
    - 1.100.101.1/16
    - 2.100.101.1/16
    mcast_subnets:
    - 225.114.0.0/16
    vlans:
    - 101
    - 102
  - cluster_profile: ckof2c2
    context:
      aep: ACI_AttEntityP
      l3out:
        external_networks:
        - default_extepg
        name: l3out
      vrf:
        name: k8s
        tenant: common
    external_subnets:
    - 20.4.0.1/16
    internal_subnets:
    - 10.6.0.1/16
    remote_as_numbers:
    - 64513
    vlans:
    - 104
  available:
    contexts:
      context-1:
        aep: ACI_AttEntityP
        l3out:
          external_networks:
          - default_extepg
          name: l3out
        vrf:
          name: k8s
          tenant: common
      context-2:
        aep: ACI_AttEntityP
        l3out:
          external_networks:
          - default_extepg
          name: l3out
        vrf:
          name: k8s
          tenant: common
    external_subnets:
    - 20.3.0.1/16
    internal_subnets:
    - 10.5.0.1/16
    - 20.2.0.1/16
    - 20.5.0.1/16
    mcast_subnets:
    - 225.115.0.0/16
    remote_as_numbers:
    - 64512
    - 64514
    vlans:
    - 103
  ready: true
