apiVersion: notification-ctrlr.netop-types.io/v1alpha1
kind: Notification
metadata:
  creationTimestamp: null
  name: ckof1c1-netop-manager-system-kube-root-ca.crt-configmap-core-v1
spec:
  clusterName: ckof1c1
  objRef:
    apiVersion: v1
    kind: ConfigMap
    name: kube-root-ca.crt
    namespace: netop-manager-system
  serializedObj: '{"kind":"ConfigMap","apiVersion":"v1","metadata":{"name":"kube-root-ca.crt","namespace":"netop-manager-system","creationTimestamp":null},"data":{"ca.crt":"-----BEGIN
    CERTIFICATE-----\nMIIC/jCCAeagAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl\ncm5ldGVzMB4XDTIzMDEzMDEzMTAyM1oXDTMzMDEyNzEzMTAyM1owFTETMBEGA1UE\nAxMKa3ViZXJuZXRlczCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALxL\nBvL0SZnu3lxRVU6vweUtaYC7fX6ijvLYaHPGmeDuJC3gpcygd498HC9jV0C55MKy\nYfsOF6ObPVn0eKhGIFYpFvvu+lfDYKA9XGxqOnecYJ6cQzL9HJ9PabHMnPgyHLt5\ndMMHgygSuHLVmLGck+8w8HFZ2C1LrXCacEZ3fCn4TsXOM49VF+Mg2KC89eqR71ww\nn7TpE9E6YQryab0uT4TVb/qeUWTBsBtxdnmSCDLnXtqsVHFj0k/yxL1iaNtU4kUi\nfXARVW4Znllo6v6e1+Mlw4lFxp7rdQgQHNCi85jFP2KZ0WtvF9aVvSa2vl2MkKxk\nhPmNdVbuYEfYvi8Z1f0CAwEAAaNZMFcwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB\n/wQFMAMBAf8wHQYDVR0OBBYEFNeyj/psdtlOpAR5TQNcxENoXWDhMBUGA1UdEQQO\nMAyCCmt1YmVybmV0ZXMwDQYJKoZIhvcNAQELBQADggEBAFJ52OyBAG9qnyIxm0Jc\nv05k5pSeMON/i2si2RuqSpLaV1OYBiZv0zpf+6l0NapCqT8AGtHkstSn9NW7Ix3X\nTgj8GVXl1/nOZxwL5+AxgazPsY8XP6IMI+b6I+YPIA6HG19S3277jJmg7kpRNfMt\nd9Ttk6lOFkMkP9oOgVkx5O599CuicJz+rLFN5Ut9BjD17u3KGJNsOEN4sKQTm/Nq\n1Chl0cgcttWbsw5kmq6QNc/OrJ8nqDS5LIV7W+fUQ2gj0jF+8m7TzxQYYWyUB4y2\npAVinvrZiJS1aRTmt73Q0wXSN2UgNeLh2LJz3AmuhTc1xQuRtdn1GyNKnap8m8r5\noE8=\n-----END
    CERTIFICATE-----\n"}}'
status:
  state: ""
